<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\PlanSlug;
use App\Models\Plan;
use Illuminate\Database\Seeder;

final class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'FREE',
                'slug' => PlanSlug::Free->value,
                'description' => 'Perfect for trying out Termio',
                'monthly_price' => 0.00,
                'yearly_price' => 0.00,
                'sort_order' => 0,
                'features' => [
                    'online_booking_widget' => true,
                    'manual_reservations' => true,
                    'calendar_view' => 'basic',
                    'client_database' => 'basic',
                    'email_confirmations' => true,
                    'email_reminders' => true,
                    'sms_reminders' => false,
                    'custom_logo' => false,
                    'custom_colors' => false,
                    'custom_booking_url' => false,
                    'custom_domain' => false,
                    'white_label' => false,
                    'google_calendar_sync' => false,
                    'payment_gateway' => false,
                    'api_access' => false,
                    'zapier_integration' => false,
                    'multi_language' => false,
                    'staff_permissions' => false,
                    'client_segmentation' => false,
                    'waitlist_management' => false,
                    'recurring_appointments' => false,
                    'gift_vouchers' => false,
                    'reports_statistics' => 'basic',
                ],
                'limits' => [
                    'reservations_per_month' => 150,
                    'users' => 1,
                    'locations' => 1,
                    'services' => 10,
                    'sms_credits_per_month' => 0,
                ],
            ],
            [
                'name' => 'EASY',
                'slug' => PlanSlug::Easy->value,
                'description' => 'For solo practitioners getting started',
                'monthly_price' => 5.90,
                'yearly_price' => 49.00,
                'sort_order' => 1,
                'features' => [
                    'online_booking_widget' => true,
                    'manual_reservations' => true,
                    'calendar_view' => 'advanced',
                    'client_database' => 'basic',
                    'email_confirmations' => true,
                    'email_reminders' => true,
                    'sms_reminders' => false,
                    'custom_logo' => true,
                    'custom_colors' => true,
                    'custom_booking_url' => true,
                    'custom_domain' => false,
                    'white_label' => false,
                    'google_calendar_sync' => true,
                    'payment_gateway' => true,
                    'api_access' => false,
                    'zapier_integration' => false,
                    'multi_language' => true,
                    'staff_permissions' => false,
                    'client_segmentation' => false,
                    'waitlist_management' => false,
                    'recurring_appointments' => true,
                    'gift_vouchers' => false,
                    'reports_statistics' => 'full',
                ],
                'limits' => [
                    'reservations_per_month' => 350,
                    'users' => 1,
                    'locations' => 1,
                    'services' => -1,
                    'sms_credits_per_month' => 0,
                ],
            ],
            [
                'name' => 'SMART',
                'slug' => PlanSlug::Smart->value,
                'description' => 'Best value for growing businesses',
                'monthly_price' => 11.90,
                'yearly_price' => 99.00,
                'sort_order' => 2,
                'features' => [
                    'online_booking_widget' => true,
                    'manual_reservations' => true,
                    'calendar_view' => 'advanced',
                    'client_database' => 'advanced',
                    'email_confirmations' => true,
                    'email_reminders' => true,
                    'sms_reminders' => true,
                    'custom_logo' => true,
                    'custom_colors' => true,
                    'custom_booking_url' => true,
                    'custom_domain' => true,
                    'white_label' => false,
                    'google_calendar_sync' => true,
                    'payment_gateway' => true,
                    'api_access' => true,
                    'zapier_integration' => true,
                    'multi_language' => true,
                    'staff_permissions' => true,
                    'client_segmentation' => true,
                    'waitlist_management' => true,
                    'recurring_appointments' => true,
                    'gift_vouchers' => true,
                    'reports_statistics' => 'full',
                ],
                'limits' => [
                    'reservations_per_month' => 1500,
                    'users' => 3,
                    'locations' => 2,
                    'services' => -1,
                    'sms_credits_per_month' => 50,
                ],
            ],
            [
                'name' => 'STANDARD',
                'slug' => PlanSlug::Standard->value,
                'description' => 'For established businesses with teams',
                'monthly_price' => 24.90,
                'yearly_price' => 199.00,
                'sort_order' => 3,
                'features' => [
                    'online_booking_widget' => true,
                    'manual_reservations' => true,
                    'calendar_view' => 'advanced',
                    'client_database' => 'advanced',
                    'email_confirmations' => true,
                    'email_reminders' => true,
                    'sms_reminders' => true,
                    'custom_logo' => true,
                    'custom_colors' => true,
                    'custom_booking_url' => true,
                    'custom_domain' => true,
                    'white_label' => false,
                    'google_calendar_sync' => true,
                    'payment_gateway' => true,
                    'api_access' => true,
                    'zapier_integration' => true,
                    'multi_language' => true,
                    'staff_permissions' => true,
                    'client_segmentation' => true,
                    'waitlist_management' => true,
                    'recurring_appointments' => true,
                    'gift_vouchers' => true,
                    'reports_statistics' => 'full',
                ],
                'limits' => [
                    'reservations_per_month' => -1,
                    'users' => 10,
                    'locations' => 10,
                    'services' => -1,
                    'sms_credits_per_month' => 200,
                ],
            ],
            [
                'name' => 'PREMIUM',
                'slug' => PlanSlug::Premium->value,
                'description' => 'Enterprise features with priority support',
                'monthly_price' => 49.90,
                'yearly_price' => 449.00,
                'sort_order' => 4,
                'features' => [
                    'online_booking_widget' => true,
                    'manual_reservations' => true,
                    'calendar_view' => 'advanced',
                    'client_database' => 'advanced',
                    'email_confirmations' => true,
                    'email_reminders' => true,
                    'sms_reminders' => true,
                    'custom_logo' => true,
                    'custom_colors' => true,
                    'custom_booking_url' => true,
                    'custom_domain' => true,
                    'white_label' => true,
                    'google_calendar_sync' => true,
                    'payment_gateway' => true,
                    'api_access' => true,
                    'zapier_integration' => true,
                    'multi_language' => true,
                    'staff_permissions' => true,
                    'client_segmentation' => true,
                    'waitlist_management' => true,
                    'recurring_appointments' => true,
                    'gift_vouchers' => true,
                    'reports_statistics' => 'full',
                ],
                'limits' => [
                    'reservations_per_month' => -1,
                    'users' => -1,
                    'locations' => -1,
                    'services' => -1,
                    'sms_credits_per_month' => -1,
                ],
            ],
        ];

        foreach ($plans as $planData) {
            Plan::updateOrCreate(
                ['slug' => $planData['slug']],
                $planData
            );
        }
    }
}
